#ifndef CSYNC_ERROR_H
#define CSYNC_ERROR_H

/*csync error*/
#define CSYNC_ERROR 1000
/*config error*/
#define CONFIG_ERROR 2000
#define CONFIG_LOAD_FILE_ERROR CONFIG_ERROR + 1
#define CONFIG_JSON_FORMAT_ERROR CONFIG_ERROR + 2
#define CONFIG_NODE_NAME_ERROR CONFIG_ERROR + 3

/*socket error*/
#define WIN_IOCP_ERROR_START 4000
#define WSAStartup_ERROR WIN_IOCP_ERROR_START + 1
#define CREATE_PORT_INVALID_HANDLE WIN_IOCP_ERROR_START + 2
#define CREATE_WORK_THREAD_ERROR WIN_IOCP_ERROR_START + 3
#define CREATE_SERVER_SOCKET_ERROR WIN_IOCP_ERROR_START + 4
#define BIND_ERROR WIN_IOCP_ERROR_START + 5
#define LISTEN_ERROR WIN_IOCP_ERROR_START + 6
#define ACCEPT_ERROR WIN_IOCP_ERROR_START + 7
#define CREATE_PORT_HANDLE WIN_IOCP_ERROR_START + 8
#define MALLOC_ERROR WIN_IOCP_ERROR_START + 9
#define WSARecv_ERROR WIN_IOCP_ERROR_START + 10

/*sync data error*/
#define SYNC_STATUS_ERROR_START 5000

#define SYNC_STATUS_ERROR_PATH SYNC_STATUS_ERROR_START+1
#define SYNC_STATUS_ERROR_CLIENT_REQ_SIG SYNC_STATUS_ERROR_START+2
#define SYNC_STATUS_ERROR_SERVER_ACK_SIG SYNC_STATUS_ERROR_START+3
#define SYNC_STATUS_ERROR_CLIENT_RECV_SIG SYNC_STATUS_ERROR_START+4
#define SYNC_STATUS_ERROR_SERVER_SEND_SIG SYNC_STATUS_ERROR_START+5
#define SYNC_STATUS_ERROR_CLIENT_SEND_DEL SYNC_STATUS_ERROR_START+6
#define SYNC_STATUS_ERROR_SERVER_RECV_DEL SYNC_STATUS_ERROR_START+7
#define SYNC_STATUS_ERROR_CLIENT_SENDING_DEL SYNC_STATUS_ERROR_START+8
#define SYNC_STATUS_ERROR_SERVER_RECV_END SYNC_STATUS_ERROR_START+9
#define SYNC_STATUS_ERROR_SERVER_PATCHED SYNC_STATUS_ERROR_START+10
#define SYNC_STATUS_ERROR_CLIENT_SEND_NEW SYNC_STATUS_ERROR_START+11
#define SYNC_STATUS_ERROR_SERVER_RECVING_NEW SYNC_STATUS_ERROR_START+12
#define SYNC_STATUS_ERROR_SERVER_RECV_NEW_END SYNC_STATUS_ERROR_START+13
#define SYNC_STATUS_ERROR_ERROR_STS SYNC_STATUS_ERROR_START+14
#define SYNC_STATUS_ERROR_ERROR_STEP SYNC_STATUS_ERROR_START+15
#define SYNC_STATUS_ERROR_FORMAT SYNC_STATUS_ERROR_START+16


/*client error*/
#define CLIENT_ERROR_START 5000
#define CLIENT_ERROR_INITIAL_SOCKET CLIENT_ERROR_START+1
#define CLIENT_ERROR_REQ_SIG CLIENT_ERROR_START+2
#define CLIENT_ERROR_REQ_NEW CLIENT_ERROR_START+3
#define CLIENT_ERROR_SEND_NEW CLIENT_ERROR_START+4
#define CLIENT_ERROR_RECV_SIG CLIENT_ERROR_START+5
#define CLIENT_ERROR_REQ_DELTA CLIENT_ERROR_START+6
#define CLIENT_ERROR_SEND_DELTA CLIENT_ERROR_START+7

#endif