#pragma once
#ifndef SM_PROTOCOL_H
#define SM_PROTOCOL_H
enum sync_status
{
    READY_BASE,
    PATH_SYNC,
    TIME_SYNC,
    READY_SYNC,
    NOTICE_SYNC_ALL,
    CLIENT_REQ_DIR,
    SERVER_ACK_DIR,
    CLIENT_REQ_FILE,
    SERVER_ACK_FILE,
    CLIENT_DEL_FILE,
    SERVER_DEL_FILE,
    CLIENT_RENAME_FILE,
    SERVER_RENAME_FILE,
    CLIENT_CHECK_FILE_E,
    CLIENT_REQ_SIG,
    SERVER_ACK_SIG,
    CLIENT_RECV_SIG,
    SERVER_SEND_SIG,
    CLIENT_SEND_DEL,
    SERVER_RECV_DEL,
    CLIENT_SENDING_DEL,
    SERVER_RECV_END,
    SERVER_PATCHED,
    CLIENT_SEND_NEW,
    SERVER_RECVING_NEW,
    SERVER_RECV_NEW_END,
    ERROR_STS
};
#endif